# Generated by Django 4.1.1 on 2022-10-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('country_number', models.IntegerField()),
                ('ext', models.CharField(blank=True, max_length=255)),
                ('ptype', models.CharField(choices=[('FIXED', 'Fixed phone number'), ('MOBILE', 'Mobile phone number')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Nombre')),
                ('object_id', models.CharField(max_length=255)),
                ('belongs_to', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Medios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EMAIL', 'Email'), ('SOCIAL_MEDIA_EMPRESA', 'Corporate e-mail'), ('MY_SOCIAL_MEDIA', 'My social media'), ('TEXT_MESSAGE', 'Text message'), ('OTHER', 'Other'), ('FB_PRIVATE_MESSAGE', 'Facebook Private Message')], max_length=255)),
                ('value', models.TextField(verbose_name='Value of informed medium')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='misc.frequency')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the company')),
                ('address', models.TextField(verbose_name='Address')),
                ('rif', models.CharField(max_length=255)),
                ('representate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL, verbose_name='representative')),
            ],
        ),
        migrations.AddIndex(
            model_name='socialmedia',
            index=models.Index(fields=['content_type', 'object_id'], name='misc_social_content_923a29_idx'),
        ),
    ]
