# Generated by Django 4.1.1 on 2022-10-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_bank', models.CharField(max_length=255, verbose_name='Bank of origin')),
                ('destination_bank', models.CharField(blank=True, max_length=255, verbose_name='Destination bank')),
                ('origin_bank_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_infos', to='country.country', verbose_name='Origin bank country')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Currency name')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Currency code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='country.country', verbose_name='Currency country')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
    ]
