# Generated by Django 4.1.2 on 2022-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('CAR', 'Car'), ('VAN', 'Van')], default='CAR', max_length=5),
        ),
    ]
